// angular/HtmlToJson/src/app/app.component.ts
import { Component } from '@angular/core';
import { JSONFromHTML } from './interfaces/json-from-html.interface';
import htmlOnJsonStructure from '../assets/html.json';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  htmlConverted = '';
  textConverted = '';

  htmlOnJson: JSONFromHTML = htmlOnJsonStructure;

  constructor(){
    console.log(this.htmlOnJson);
    this.htmlConverted = this.parseJsonStructureToHtml(this.htmlOnJson);
    this.textConverted = this.parseJsonStructureToText(this.htmlOnJson);
  }  


  parseJsonStructureToHtml(node: JSONFromHTML):string {
    var html: string = '';
    if (node.children.length > 0) {
      if (this.isValidTag(node.tag)) {
        html += `<${node.tag}>`;        
      }
      node.children.forEach(element => {
        html += `${this.parseJsonStructureToHtml(element)}`;
      });
      if (this.isValidTag(node.tag)) {
        html += `</${node.tag}>`;
      }
    } else {
      if (this.isValidTag(node.tag)) {
        html += `<${node.tag}>${node.text}</${node.tag}>`;
      }
    }
    return html;
  }

  parseJsonStructureToText(node: JSONFromHTML):string {
    var html: string = '';
    if (node.children.length > 0) {
      node.children.forEach(element => {
        html += `${this.parseJsonStructureToText(element)}`;
      });
    } else {
      if (this.isValidTag(node.tag)) {
        html += `${node.text} `;
      }
    }
    return html;
  }

  isValidTag(tag: string | null):boolean {
    if (tag && tag != 'html' && tag != 'body' && tag != 'head') {
      return true;
    }
    return false;
  }
}

<h2>JSON</h2>

<hr>

<div><pre [innerHTML]="htmlOnJson | json"></pre></div>

<h2>HTML</h2>

<hr>

<div [innerHTML]="htmlConverted"></div>

<h2>TEXT</h2>

<hr>

<div [innerHTML]="textConverted"></div>

// react/json-to-html/src/App.tsx
import React from 'react';
import logo from './logo.svg';
import './App.css';
import { JSONFromHTML } from './interfaces/json-from-html.interface';
import htmlOnJsonStructure from './html.json';


let htmlConverted = '';
let textConverted = '';

let htmlOnJson: JSONFromHTML = htmlOnJsonStructure;

function App() {
  htmlConverted = parseJsonStructureToHtml(htmlOnJson);
  textConverted = parseJsonStructureToText(htmlOnJson);

  return (
    <div className="App">
      <h2>JSON</h2>
      <hr></hr>
      <pre>{JSON.stringify(htmlOnJson, undefined, 2)}</pre>
      <h2>TEXT</h2>
      <hr></hr>
      {textConverted}
      <h2>HTML</h2>
      <hr></hr>
      <div dangerouslySetInnerHTML={{ __html: htmlConverted }} />
    </div>
  );
}

function parseJsonStructureToHtml(node: JSONFromHTML):string {
  var html: string = '';
  if (node.children.length > 0) {
    if (isValidTag(node.tag)) {
      html += `<${node.tag}>`;        
    }
    node.children.forEach(element => {
      html += `${parseJsonStructureToHtml(element)}`;
    });
    if (isValidTag(node.tag)) {
      html += `</${node.tag}>`;
    }
  } else {
    if (isValidTag(node.tag)) {
      html += `<${node.tag}>${node.text}</${node.tag}>`;
    }
  }
  return html;
}

function parseJsonStructureToText(node: JSONFromHTML):string {
  var html: string = '';
  if (node.children.length > 0) {
    node.children.forEach(element => {
      html += `${parseJsonStructureToText(element)}`;
    });
  } else {
    if (isValidTag(node.tag)) {
      html += `${node.text} `;
    }
  }
  return html;
}

function isValidTag(tag: string | null):boolean {
  if (tag && tag != 'html' && tag != 'body' && tag != 'head') {
    return true;
  }
  return false;
}
export default App;
