// react/05-hook-test/src/components/09-useContext/NavBar.js
import { NavLink } from "react-router-dom";

export const NavBar = () => {
    return (
        <nav className="navbar navbar-expand-sm navbar-dark bg-dark">
            <div className="container-fluid">
                <NavLink activeClassName="active" className="navbar-brand" to="/">useContextApp</NavLink>
                <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>                
                <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div className="navbar-nav">
                    <NavLink exact activeClassName="active" className="nav-link" to="/">Home</NavLink>
                    <NavLink exact activeClassName="active" className="nav-link" to="/login">Login</NavLink>
                    <NavLink exact activeClassName="active" className="nav-link" to="/about">About</NavLink>
                </div>
                </div>
            </div>
        </nav>            
    )
}

// angular/02-spa/src/app/components/shared/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';


@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor(private router: Router) { }

  ngOnInit(): void {
  }

  buscarHeroe(heroe: string) {
    this.router.navigate(['/buscar', heroe]);
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="assets/images/A-64.png" alt="" width="30" height="24">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item" routerLinkActive="active font-weight-bolder">
                    <a class="nav-link" [routerLink]="['home']">Home</a>
                </li>
                <li class="nav-item" routerLinkActive="active font-weight-bolder">
                    <a class="nav-link" [routerLink]="['heroes']">Héroes</a>
                </li>
                <li class="nav-item" routerLinkActive="active font-weight-bolder">
                    <a class="nav-link" [routerLink]="['about']">About</a>
                </li>
            </ul>
            <!-- <form class="d-flex"> -->
            <input class="form-control me-2" type="search" placeholder="Buscar héroe" aria-label="Buscar" (keyup.enter)="buscarHeroe(buscarTexto.value)" #buscarTexto>
            <button (click)="buscarHeroe(buscarTexto.value)" class="btn btn-outline-light" type="button">Buscar</button>
            <!-- </form> -->
        </div>
    </div>
</nav>
