// angular/02-spa/src/app/components/shared/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';


@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor(private router: Router) { }

  ngOnInit(): void {
  }

  buscarHeroe(heroe: string) {
    this.router.navigate(['/buscar', heroe]);
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="assets/images/A-64.png" alt="" width="30" height="24">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item" routerLinkActive="active font-weight-bolder">
                    <a class="nav-link" [routerLink]="['home']">Home</a>
                </li>
                <li class="nav-item" routerLinkActive="active font-weight-bolder">
                    <a class="nav-link" [routerLink]="['heroes']">Héroes</a>
                </li>
                <li class="nav-item" routerLinkActive="active font-weight-bolder">
                    <a class="nav-link" [routerLink]="['about']">About</a>
                </li>
            </ul>
            <!-- <form class="d-flex"> -->
            <input class="form-control me-2" type="search" placeholder="Buscar héroe" aria-label="Buscar" (keyup.enter)="buscarHeroe(buscarTexto.value)" #buscarTexto>
            <button (click)="buscarHeroe(buscarTexto.value)" class="btn btn-outline-light" type="button">Buscar</button>
            <!-- </form> -->
        </div>
    </div>
</nav>

// react/07-heroes-app/src/components/ui/NavBar.js
// Sacar el código para no tener que volver a hacer todo

import React from 'react';
import { Link, NavLink } from 'react-router-dom';

export const Navbar = () => {
    return (
        <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
            <div className="container-fluid">
                <Link className="navbar-brand" to="/">Asociaciones</Link>
                <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarSupportedContent">
                    <div className="navbar-nav">
                        <NavLink 
                            activeClassName="active"
                            className="nav-item nav-link" 
                            exact
                            to="/marvel"
                        >Marvel
                        </NavLink>

                        <NavLink 
                            activeClassName="active"
                            className="nav-item nav-link" 
                            exact
                            to="/dc"
                        >DC
                        </NavLink>
                    </div>
                    <div className="d-flex flex-row-reverse w-100">
                        <ul className="navbar-nav">
                            <NavLink 
                                activeClassName="active"
                                className="nav-item nav-link" 
                                exact
                                to="/login"
                            >Logout
                            </NavLink>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    )
}
